
# Use the official Airflow image as a base
FROM apache/airflow:2.7.0-python3.8

ENV AIRFLOW_PROJ_DIR=C:/Users/jagad/OneDrive/Desktop/PayNearby-DataEngineering-Assignment/etl-de-project/docker


# Install additional Python packages
RUN pip install pandas sqlalchemy psycopg2-binary
